version: "3"
label: "tree"
services:
  app:
    ports:
        -    "5505:5000"
    build:
      context: ./app
      dockerfile: Dockerfile_app
  tester:
    build:
      context: ./test
      dockerfile: Dockerfile_tester
    depends_on:
      - app
    ports:
        -    "5033:22"
